In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("Bengaluru_House_Data.csv")
data.head()
data.columns = data.columns.str.strip()

In [3]:
data.shape

(13320, 9)

In [4]:
data.info

<bound method DataFrame.info of                   area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II
1                Plot  Area  Ready To Move          Chikka Tirupathi
2            Built-up  Area  Ready To Move               Uttarahalli
3      Super built-up  Area  Ready To Move        Lingadheeranahalli
4      Super built-up  Area  Ready To Move                  Kothanur
...                     ...            ...                       ...
13315        Built-up  Area  Ready To Move                Whitefield
13316  Super built-up  Area  Ready To Move             Richards Town
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar
13318  Super built-up  Area         18-Jun           Padmanabhanagar
13319  Super built-up  Area  Ready To Move              Doddathoguru

            size  society total_sqft  bath  balcony   price
0          2 BHK  Coomee        1056   2.0      1.0   39.07
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00
2          3 BHK      NaN       1440   2.0      3.0   62.00
3          3 BHK  Soiewre       1521   3.0      1.0   95.00
4          2 BHK      NaN       1200   2.0      1.0   51.00
...          ...      ...        ...   ...      ...     ...
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00
13316      4 BHK      NaN       3600   5.0      NaN  400.00
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00
13319      1 BHK      NaN        550   1.0      1.0   17.00

[13320 rows x 9 columns]>

In [5]:
for column in data.columns:
    print(data[column].value_counts())

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
society
GrrvaGr    80
PrarePa    76
Prtates    59
Sryalan    59
GMown E    56
           ..
SNadeAr     1
DSellil     1
Shensit     1
VKvenas     1
Vemes H     1
Name: count, Length: 2688, dtype: int64
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64

In [6]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [7]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [8]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [10]:
data['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [11]:
data['location']=data['location'].fillna("Sarjapur Road")

In [12]:
 data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [13]:
data['size'] = data['size'].fillna('2 BHK')
data['bath'] = data['bath'].fillna(data['bath'].median())

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [15]:
data['bhk'] = data['size'].str.split().str.get(0).astype(int)

In [16]:
data[data.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [17]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [18]:
def convertRange(x):
    temp= str(x).split('-')
    if len(temp) == 2:
     return (float(temp[0]) + float(temp[1])) / 2
    try:
        return float(x)
    except:
        return None

In [19]:
data['total_sqft'] = data['total_sqft'].apply(convertRange)
data['total_sqft'] = pd.to_numeric(data['total_sqft'], errors='coerce')
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [20]:
data = data.dropna(subset=['total_sqft'])
data['price_per_sqft'] = data['price'] *100000/data['total_sqft']

C:\Users\BAPS\AppData\Local\Temp\ipykernel_10632\359035837.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['price_per_sqft'] = data['price'] *100000/data['total_sqft']

In [21]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13274, dtype: float64

In [22]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13274.000000  13274.000000  13274.000000    1.327400e+04
mean    1559.626694      2.687359    112.453654      2.801718    7.907501e+03
std     1238.405258      1.336158    149.070368      1.291591    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [23]:
data['location'].value_counts()

location
Whitefield                           538
Sarjapur  Road                       399
Electronic City                      302
Kanakpura Road                       271
Thanisandra                          233
                                    ...
Beml layout, Rajarajeshwari nagar      1
Duddanahalli                           1
Doddanakunte                           1
Jogupalya                              1
Subhash Nagar                          1
Name: count, Length: 1300, dtype: int64

In [25]:
data.loc[:, 'location'] = data['location'].apply(lambda x: x.strip())
location_count = data['location'].value_counts()

In [26]:
location_count_less_10 = location_count[location_count<=10]
location_count_less_10

location
BTM 1st Stage                        10
Nagappa Reddy Layout                 10
Sector 1 HSR Layout                  10
Ganga Nagar                          10
Basapura                             10
                                     ..
Zuzuvadi                              1
Chellikere                            1
Jakkasandra                           1
Gulakamale                            1
Beml layout, Rajarajeshwari nagar     1
Name: count, Length: 1049, dtype: int64

In [27]:
data.loc[:, 'location'] = data['location'].apply(
    lambda x: 'other' if x in location_count_less_10 else x
)

In [28]:
data['location'].value_counts()

location
other                        2877
Whitefield                    539
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                271
                             ...
2nd Phase Judicial Layout      11
Marsur                         11
Bommenahalli                   11
Doddaballapur                  11
HAL 2nd Stage                  11
Name: count, Length: 241, dtype: int64

In [29]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13274.000000  13274.000000  13274.000000    1.327400e+04
mean    1559.626694      2.687359    112.453654      2.801718    7.907501e+03
std     1238.405258      1.336158    149.070368      1.291591    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [30]:
data = data[data['total_sqft']/data['bhk'] >= 300]
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12530.000000  12530.000000  12530.000000  12530.000000    12530.000000
mean    1594.564544      2.559537    111.382401      2.650838     6303.979357
std     1261.271296      1.077938    152.077329      0.976678     4162.237981
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     16.000000   3600.000000     16.000000   176470.588235

In [31]:
data.shape

(12530, 7)

In [32]:
def remove_outlier(df):
    df_output = pd.DataFrame()
    for kry,subdf in df.groupby('location'): ##groupby lagavi aetle key aape and aeno subdata aape subdf aetle subdata
        
        m = np.mean(subdf.price_per_sqft)

        st = np.std(subdf.price_per_sqft)

        gen_df = subdf[(subdf.price_per_sqft> (m-st)) & (subdf.price_per_sqft <= (m+st))]
        df_output = pd.concat([df_output,gen_df],ignore_index=True)
    return df_output
data = remove_outlier(data)
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10302.000000  10302.000000  10302.000000  10302.000000    10302.000000
mean    1508.585392      2.472044     91.294983      2.575325     5659.095970
std      880.774066      0.980018     86.343018      0.898664     2265.667258
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.994224
50%     1286.000000      2.000000     67.000000      2.000000     5175.792088
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     16.000000   2200.000000     16.000000    24509.803922

In [33]:
print(data.columns)

Index(['location', 'size', 'total_sqft', 'bath', 'price', 'bhk',
       'price_per_sqft'],
      dtype='object')

In [34]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [35]:
def bhk_outlier (df):
    exclude_indices = np.array([])
    for location,location_df in df.groupby("location"):
        bhk_stats = {}
        for bhk,bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                "mean": np.mean(bhk_df.price_per_sqft),
                "std": np.std(bhk_df.price_per_sqft),
                "count": bhk_df.shape[0]}
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices,bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')

In [36]:
data =bhk_outlier(data)

In [37]:
data.shape

(7348, 7)

In [38]:
# price_per_sqft outlier mate banvyu tu
data.drop(columns=["size","price_per_sqft"],inplace=True)

In [39]:
data

                  location  total_sqft  bath  price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.0    4
1      1st Block Jayanagar      1630.0   3.0  194.0    3
2      1st Block Jayanagar      1875.0   2.0  235.0    3
3      1st Block Jayanagar      1200.0   2.0  130.0    3
4      1st Block Jayanagar      1235.0   2.0  148.0    2
...                    ...         ...   ...    ...  ...
10293                other      1200.0   2.0   70.0    2
10294                other      1800.0   1.0  200.0    1
10297                other      1353.0   2.0  110.0    2
10298                other       812.0   1.0   26.0    1
10301                other      3600.0   5.0  400.0    4

[7348 rows x 5 columns]

In [40]:
data.to_csv("clean_house.csv")

In [41]:
x = data.drop(columns=["price"])
y = data["price"]

In [42]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [43]:
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=23)

In [44]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output=False),['location']),
                                       remainder = 'passthrough')

In [45]:
scaler = StandardScaler()

In [46]:
lr = LinearRegression()

In [47]:
pipe = make_pipeline(column_trans,scaler,lr)

In [48]:
pipe.fit(x_train,y_train)

C:\Users\BAPS\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [49]:
y_pred = pipe.predict(x_test)

In [50]:
r2_score(y_test,y_pred)

0.8599721470987141

## Lasso

In [51]:
lasso = Lasso()

In [52]:
pipe = make_pipeline(column_trans,scaler,lasso)

In [53]:
pipe.fit(x_train,y_train)

C:\Users\BAPS\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [54]:
y_pred_lasso= pipe.predict(x_test)
r2_score(y_test,y_pred_lasso)

0.8501851592711754

## Ridge

In [55]:
ridge = Ridge()

In [56]:
pipe = make_pipeline(column_trans,scaler,ridge)

In [57]:
pipe.fit(x_train,y_train)

C:\Users\BAPS\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [58]:
y_pred_ridge=pipe.predict(x_test)
r2_score(y_test,y_pred_ridge)

0.8599543540299321

In [59]:
print("NO Regularization:",r2_score(y_test,y_pred)*100)
print("Ridge:",r2_score(y_test,y_pred_ridge)*100)
print("Lasso:",r2_score(y_test,y_pred_lasso)*100)

NO Regularization: 85.9972147098714
Ridge: 85.99543540299321
Lasso: 85.01851592711755

In [60]:
import pickle

In [61]:
pickle.dump(pipe,open("ridgemodelss.pkl","wb"))

In [62]:
import pickle

model = pickle.load(open('ridgemodel.pkl', 'rb'))

In [63]:
print(model)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [64]:
!pip install ipywidgets

Requirement already satisfied: ipywidgets in c:\users\baps\anaconda3\lib\site-packages (8.1.5)
Requirement already satisfied: comm>=0.1.3 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipywidgets) (9.10.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\users\baps\anaconda3\lib\site-packages (from ipywidgets) (4.0.13)
Requirement already satisfied: jupyterlab_widgets~=3.0.12 in c:\users\baps\anaconda3\lib\site-packages (from ipywidgets) (3.0.13)
Requirement already satisfied: colorama>=0.4.4 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\baps\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\baps\appdata\roaming\python\python313\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\baps\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

In [65]:
!pip install ipywidgets jupyterlab_widgets

Requirement already satisfied: ipywidgets in c:\users\baps\anaconda3\lib\site-packages (8.1.5)
Requirement already satisfied: jupyterlab_widgets in c:\users\baps\anaconda3\lib\site-packages (3.0.13)
Requirement already satisfied: comm>=0.1.3 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipywidgets) (9.10.0)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\users\baps\anaconda3\lib\site-packages (from ipywidgets) (4.0.13)
Requirement already satisfied: colorama>=0.4.4 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\baps\appdata\roaming\python\python313\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\baps\appdata\roaming\python\python313\site-packages (from jedi>=0.18.1->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\baps\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in c:\users\baps\appdata\roaming\python\python313\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)

In [66]:
import ipywidgets as widgets
widgets.IntSlider()

IntSlider(value=0)

In [ ]:
print(model)

##widged

In [71]:
# Load model
model = pickle.load(open('ridgemodel.pkl', 'rb'))

# Get only trained locations
locations = model.named_steps['columntransformer'] \
                 .named_transformers_['onehotencoder'] \
                 .categories_[0]

locations = sorted(locations)

# Widgets
import ipywidgets as widgets
from IPython.display import display
import pandas as pd

area = widgets.FloatText(description="Area")
bed = widgets.IntText(description="Bedrooms")
bath = widgets.IntText(description="Bathrooms")

location = widgets.Dropdown(
    options=locations,
    description="Location"
)

output = widgets.Output()
button = widgets.Button(description="Predict")

def predict(b):
    with output:
        output.clear_output()
        try:
            input_data = pd.DataFrame({
                'total_sqft': [area.value],
                'bhk': [bed.value],
                'bath': [bath.value],
                'location': [location.value]
            })

            result = model.predict(input_data)
            price = result[0]

            if price < 0:
                print("⚠️ Invalid input / unrealistic house details")
            else:
                print("Price:", round(price, 2),"Lacs")

        except Exception as e:
            print("Error:", e)

button.on_click(predict)

display(area, bed, bath, location, button, output)

FloatText(value=0.0, description='Area')

IntText(value=0, description='Bedrooms')

IntText(value=0, description='Bathrooms')

Dropdown(description='Location', options=('1st Block Jayanagar', '1st Phase JP Nagar', '2nd Phase Judicial Lay…

Button(description='Predict', style=ButtonStyle())

Output()

In [ ]:
%%writefile app.py
# (yaha poora Streamlit code paste kar)
import streamlit as st
import numpy as np
import pickle

# load your trained model
model = pickle.load(open('ridgemodel.pkl', 'rb'))

st.title("🏠 House Price Prediction")

# Inputs
area = st.number_input("Area (sq ft)", min_value=0)
bed = st.number_input("Bedrooms", min_value=0)
bath = st.number_input("Bathrooms", min_value=0)
location = st.selectbox("Location", ["Banjara Layout", "Whitefield", "Indiranagar"])

# Predict button
if st.button("Predict"):
    try:
        # example input (modify according to your model)
        input_data = np.array([[area, bed, bath, 0]])  # location encoding change karna padega

        price = model.predict(input_data)[0]

        if price < 0:
            st.error("⚠ Invalid input / unrealistic house details")
        else:
            st.success(f"💰 Price: {round(price, 2)} Lacs")

    except Exception as e:
        st.error(f"Error: {e}")

In [ ]:
!streamlit run app.py